// app/(tabs)/habitMain.styles.ts
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff", paddingHorizontal: 16, paddingTop: 24 },
  header: { marginBottom: 12 },
  title: { fontSize: 20, fontWeight: "bold" },
  subTitle: { fontSize: 12, color: "#666", marginTop: 4 },
  row: { flexDirection: "row", alignItems: "center", paddingVertical: 12 },
  habit: { flex: 1, fontSize: 16 },
  buttons: { flexDirection: "row", gap: 8 },
  btn: { paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: "#ccc", borderRadius: 8 },
  btnActive: { backgroundColor: "#222" },
  btnText: { color: "#222" },
  btnTextActive: { color: "#fff", fontWeight: "bold" },
  sep: { height: 1, backgroundColor: "#eee" },
  empty: { flex: 1, alignItems: "center", justifyContent: "center" },
  emptyText: { color: "#888" },
  fab: {
    position: "absolute",
    right: 16,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#222",
    elevation: 4,
  },
  fabText: { color: "#fff", fontSize: 28, marginTop: -2 },
  modalWrap: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: { width: "86%", backgroundColor: "#fff", borderRadius: 12, padding: 16 },
  modalTitle: { fontSize: 16, fontWeight: "bold" },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    backgroundColor: "#fafafa",
  },
  modalBtns: { flexDirection: "row", justifyContent: "flex-end", gap: 12 },
  mBtn: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 8, backgroundColor: "#eee" },
  mBtnPrimary: { backgroundColor: "#222" },
});
